### ISSUE TITLE
mqtt-over-websocket support please?

### ISSUE THREAD

**Issue by aleks-mariusz** [adlerre/obd2-mqtt#15]
Apologies if this is already supported, but for lack of clear-guidance on (alternatively) how to do mqtt-federation (i haven't looked into it in combination w/ homeassistant), i thought I could *just use the cloudflared add-on* for homeassistant with [an additional-host entry](https://community.home-assistant.io/t/external-mqtt-sensor-through-cloudflare/558141/4?u=aleksmk) to make my MQTT broker (mosquitto, setup through the mqtt add-on) access on the internet.

However, to use cloudflared add-on requires a protocol that runs either over HTTP or HTTPS, which for MQTT is possible only via websocket (to my knowledge).  Now as i posted in the write-up linked above, i got this working so i can talk to my homeassistant mosquitto broker externally via websockets, but I am not sure if mqtt-over-websocket works for your fantastic mdb2-mqtt project?

Thus, how does one (or can one even) use the MQTT information specified to use mqtt-over-websocket protocol (rather than the mqtt-protocol directly) ?

**Comment by adlerre** [comment]
No isn't supported. But i think we should keep it simple. Easiest way to connect to you MQTT broker is to use D(yn)DNS and Port-Forwarding, thats it.

**Comment by aleks-mariusz** [comment]
Hmm.. well hypothetically speaking is it an unreasonable amount of work to implement websocket? I would presume it's just an extra library or something.. Or is there some limitation on the hardware of some kind that's difficult to overcome (other than the extra effort to add support).

I'm asking because i don't quite agree that port-forwarding is the best choice here, as it pokes holes in your home firewall and exposes your internal mqtt broker to the internet (whereas at least with the ddos-protection from cloudflare you have a certain level of brute-force protection), opening your mqtt broker to the internet likely means it can and will be found, and bad people will try to abuse it (i get a ton of scans on my home router IP, even if i stop responding to ICMP).

> But i think we should keep it simple

I agree that simple is _usually_ better, but i would argue that only when it does not come at the expensive of security.  I would prefer to end up using port-forwarding only as an absolute last resort, due to the port-forwarding's security-implications.

If it's a matter of effort, I can give it a try (tho i have never looked at programming an esp32 (not even with esp32) but have updated a 3d printer firmware via the arduino IDE once ages ago)?  Really want to see this project succeed, and since given the simplicity of what I came up with (more safely) exposing your mqtt broker via cloudflared, it would be far preferable to just have this product be able to support websockets.

**Comment by adlerre** [comment]
Okay, I understand your concerns.
After a quick search in the PubsubClient, there is no support for WS, but I found an issue from 2018 with the same request. This does add another layer though of complexity, but I'll try it!
Give me some days make the setup and test against.

**Comment by aleks-mariusz** [comment]
Incredible, thanks for considering it.  I wish i could help but i don't even have a sim card yet to try this.  Here's all i can for the moment contribute - a chatgpt query, the results of which are:

### ---> from ChatGPT:

To enable WebSocket support for your MQTT connection using the PubSubClient library on Arduino, you'll need to extend the functionality of your code to use a WebSocket transport layer, as PubSubClient itself does not directly support WebSockets out of the box. The PubSubClient library typically communicates over TCP for MQTT.

To enable WebSocket support, you will need to use a library that provides WebSocket communication, such as the `WebSocketsClient` library for Arduino. Then, you can integrate the WebSocket client with the PubSubClient for MQTT transport over WebSockets.

Here's a step-by-step guide:

### 1. Install the `WebSocketsClient` Library
Install the `WebSocketsClient` library via the Arduino Library Manager or manually from GitHub.

### 2. Modify Your Code
You will need to:
- Replace the direct TCP client in the PubSubClient object with a WebSocket client.
- Adjust the `connect` function to initiate a WebSocket connection before connecting to the MQTT broker.

Here's a high-level outline of what your code might look like after integrating WebSocket support:

```cpp
#include <PubSubClient.h>
#include <WebSocketsClient.h>
#include <WiFi.h>  // Assuming you're using WiFi

// Declare the WebSocket and MQTT client objects
WebSocketsClient webSocketClient;
PubSubClient mqttClient(webSocketClient);

void connect(const char *clientId, const char *broker, unsigned int port, const char *username,
             const char *password) {
    // Initialize the WebSocket client to connect to the broker
    webSocketClient.begin(broker, port, "/mqtt");  // "/mqtt" is typically the URI for MQTT over WebSocket

    // Set callback for WebSocket events (optional)
    webSocketClient.onEvent(webSocketEvent);

    // Initialize the MQTT client with the WebSocket client as the transport layer
    mqttClient.setServer(broker, port);

    // Handle WebSocket connection
    webSocketClient.connect(clientId);

    // Connect to the MQTT broker
    if (mqttClient.connect(clientId, username, password)) {
        Serial.println("Connected to MQTT broker via WebSocket!");
    } else {
        Serial.println("Failed to connect to MQTT broker via WebSocket!");
    }
}

void webSocketEvent(WStype_t type, uint8_t *payload, size_t length) {
    // Handle WebSocket events (e.g., connection open, message received)
    if (type == WStype_CONNECTED) {
        Serial.println("WebSocket Connected!");
    } else if (type == WStype_DISCONNECTED) {
        Serial.println("WebSocket Disconnected!");
    } else if (type == WStype_TEXT) {
        Serial.printf("WebSocket message: %s\n", payload);
    }
}

void setup() {
    // Setup your WiFi and other initialization code

    // Call the connect function to establish the MQTT connection via WebSocket
    connect("clientId", "broker-address", 8083, "username", "password");  // Port 8083 is typical for MQTT over WebSocket
}

void loop() {
    // Maintain the WebSocket connection
    webSocketClient.loop();

    // Maintain the MQTT connection
    if (!mqttClient.connected()) {
        connect("clientId", "broker-address", 8083, "username", "password");
    }
    mqttClient.loop();
}
```

### Key Changes:
1. **WebSocket Client Initialization**: You need to initialize the WebSocket client and point it to the MQTT broker’s WebSocket port and URI.
   - The WebSocket port is often `8083` (or another port specific to your broker), and the path is typically `/mqtt`.
   
2. **WebSocket as Transport**: The `PubSubClient` constructor accepts the WebSocket client as the transport layer instead of the default TCP client.

3. **Connect Over WebSocket**: Your `connect` function now sets up the WebSocket connection and then uses it for MQTT.

4. **Event Handling**: You can handle WebSocket-specific events like connection establishment, disconnection, or messages if needed.

### Notes:
- Make sure that your MQTT broker supports WebSocket connections. If it doesn’t, WebSocket-based communication won’t work.
- The WebSocket connection typically requires a different port (often `8083` instead of the default `1883` for MQTT over TCP).

This should allow you to use WebSocket as the transport for your MQTT communication in the Arduino environment!

### <--- end ChatGPT output

So i don't know if this is accurate or helps, but maybe it'll help you spend less time searching? Or perhaps it'll be completely useless (sometimes chatgpt can be), but want to do whatever I can to help out!

**Comment by adlerre** [comment]
I have implemented the MQTT connection via WebSocket. This has been tested with the Mosquitto WebSocket connector and works. However, the transmission is significantly slower but stable.

**Comment by aleks-mariusz** [comment]
once again, incredible work done so quickly! 

One thing, could you elaborate a bit more on "transmission is significantly slower" <-- in terms of what, i understand going throubh websocket likely has some overhead but does it mean we can't send updates as often (if so, what are the limits you saw?)..

looking forward to the version i can leverage this

**Comment by adlerre** [comment]
> once again, incredible work done so quickly!

thx

> "transmission is significantly slower"

Means, with my normal 4g sim card sensor data needs ~800ms to send over plain mqtt and over websocket ~1300ms. I tested that also with my bandwidth throttled IoT sim card (1 MBit/s) plain needs ~1100ms and over websocket nearbe ~2000ms.
This is no issue but it's slower. ;)

> looking forward to the version i can leverage this

Release is done!
