### ISSUE TITLE
Add visual input validation

### ISSUE THREAD

**Issue by marcoraddatz** [adlerre/obd2-mqtt#17]
Right now, the inputs are validated, but it's not clear, why the "save" button is disabled. I think it might be a good and relatively easy feature to show validation errors (e.g. "PIN is not a number", "APN is required", etc.).

Also, it might be good to visually highlight the required inputs with an asterisks. 

![CleanShot 2024-10-22 at 18 21 42](https://github.com/user-attachments/assets/f57f6b4a-bce2-418b-8e96-94bedac9dc0d)

**Comment by adlerre** [comment]
It sounds a little bit weird, but want save some space and don't use error descriptions.
The UI needs currently 140k and the partition size is only 196k.
But now required fields marked directly.

**Comment by marcoraddatz** [comment]
What about using HTMX instead of Angular? From my experience, this would shrink the size to less than 100k.

**Comment by adlerre** [comment]
Because i‘m love Angular. 
Was der Bauer nicht kennt… 😆
