### ISSUE TITLE
Enhancement idea: Wireguard support

### ISSUE THREAD

**Issue by spitfire** [adlerre/obd2-mqtt#20]
Hi,

I'd rather not expose my MQTT broker to the internet, but I do have Wireguard server installed on my router. I know ESPHome has a component to connect using that, so it should be possible on esp32 devices. would you consider adding that?

**Comment by adlerre** [comment]
Hi,
sorry, but i don't want to support any kind of VPN. If you don't want to expose your broker to the internet, use a free MQTT provider and subscribe to the topic with your HA.

René

**Comment by spitfire** [comment]
Can I do that even when I'm already using an MQTT broker installed on my system?

**Comment by adlerre** [comment]
Not directly! But it's thinkable to build a MQTT-Proxy-Service, with a connection to the public server witch push the topics to the HA MQTT.
This should easily done with Node and [MQTT.js](https://github.com/mqttjs/MQTT.js).

**Comment by adlerre** [comment]
Hope that's help -> #21

**Comment by spitfire** [comment]
thanks, I'll take a look at it!
