### ISSUE TITLE
No values ​​from car VW e-UP

### ISSUE THREAD

**Issue by sstuercke** [adlerre/obd2-mqtt#25]
Hi René,
the connection to the MQTT broker works.
However, no values ​​are read on my VW e-UP.
Is the VW e-Up not supported?

[VWeUP.txt](https://github.com/user-attachments/files/17721724/VWeUP.txt)

**Comment by adlerre** [comment]
Hi,

I can't say whether it is supported or not. Because I've never tested it with an EV.

If you want to help me, you can check the box for "Check if PID is supported" in the settings and test it again on your car. After that, I'm interested in the values ​​for supportedPids_*.

**Comment by sstuercke** [comment]
Hi René, 
here are the supportedPids.
13e02f8d5d6d_supportedPids_1_20 = 10000000000010000000000000010001
13e02f8d5d6d_supportedPids_21_40 = 10000000000010000000000000010001
13e02f8d5d6d_supportedPids_41_60 = 1110000010000000000000000000000000
13e02f8d5d6d_supportedPids_61_80 = 11000100110000111000000000100001

Of interest is the SoC and whether it is connected to the wallbox.
I have also enclosed a protocol.
[esp-web-tools-logs.txt](https://github.com/user-attachments/files/17749123/esp-web-tools-logs.txt)
[VWeUP.txt](https://github.com/user-attachments/files/17749126/VWeUP.txt)


Thanks

**Comment by adlerre** [comment]
Thank you, that helps me a lot. I'm analyzing it and trying to implement support. But please be patient, as I'm currently working on a major rebuild.

But I could provide a branch for testing in the meantime.

**Comment by sstuercke** [comment]
It would be good if I could test it.

**Comment by adlerre** [comment]
Would you test this branch with your car? If you need help compiling, let me know.

**Comment by sstuercke** [comment]
Unfortunately I won't be able to test it until the weekend.

**Comment by sstuercke** [comment]
I get an error message during the build.
[build.txt](https://github.com/user-attachments/files/17875749/build.txt)

**Comment by adlerre** [comment]
[eUP-Test.zip](https://github.com/user-attachments/files/17876124/eUP-Test.zip) use OTA to update

**Comment by sstuercke** [comment]
Hi René,
I tried the firmware and the SOC is coming through in MQTT.
There is only a difference between the car display 64% and MQTT 62%.
But that is because the car display 0% is not battery 0% but 10%.
When will this be included in the original version?

Thanks

**Comment by adlerre** [comment]
Hi,
thanks for testing. Sounds great that it works.

I'm planning a complete overhaul of how OBD PIDs are handled. It should be possible to define your own PIDs and save them as a profile. For this I need to implement an expression parser and a GUI to change/add the profile.
I hope to get this done this year.

René

**Comment by sstuercke** [comment]
Then I have another suggestion for improvement: make the inputs/outputs controllable via MQTT. I only need the SOC value when the car is connected to the wallbox. I want to switch off the OBD adapter.
