### ISSUE TITLE
Build files in releases

### ISSUE THREAD

**Issue by marcoraddatz** [adlerre/obd2-mqtt#3]
Hey @adlerre,

This looks like a very promising project! 

I‘ve seen that you added CI two hours ago that builds bin files. So I ask myself, whether the artifacts should be added to the pull requests and/or releases to provide an easier start for new users? I could help with that if wanted.

Best,
Marco

**Comment by adlerre** [comment]
Hey @marcoraddatz,

this planned, but I want do some changes before first release.

I think in the next days I'm done and make one.

Best
René

**Comment by adlerre** [comment]
First Release is done!

**Comment by marcoraddatz** [comment]
Wow, thanks! 

Will test it with a 7670 within the next weeks.
