### ISSUE TITLE
MQTT passwords are cut after 31 chars

### ISSUE THREAD

**Issue by marcoraddatz** [adlerre/obd2-mqtt#39]
I updated the whole software from 0.4 to 0.11 and had to re-setup all credentials. While doing so, I created a separated MQTT user for this project and unfortunately set the password length to 32 characters (yes, I know it's embedded and shouldn't be that long...). It took some time to find out the reason it's not been working - the password was missing the last character.

I think the password length should either be mentioned or validated 😉

**Comment by adlerre** [comment]
ups....

**Comment by adlerre** [comment]
add space for the null terminator

**Comment by marcoraddatz** [comment]
You're welcome! Thanks for fixing it!
