### ISSUE TITLE
ESPHome Web support

### ISSUE THREAD

**Issue by marcoraddatz** [adlerre/obd2-mqtt#4]
I see that this project supports Home Assistant and is based on ESP32 chips, so I was wondering if it’s possible to support the flashing via ESPHome Web as well?! (Got inspired by [AI on the edge](https://jomjol.github.io/AI-on-the-edge-device-docs/Installation/) and [OpenDTU](https://www.opendtu.solar/firmware/flash_esp/).)

Warning: I have no experience using PIO with ESPHome Web, so this idea might be completely off.

**Comment by adlerre** [comment]
Sounds like a plan! ;) 
After release I'm try to implement ESP-Web-Tools. [This](https://github.com/witnessmenow/ESP-Web-Tools-Tutorial) should a good starting point.

**Comment by adlerre** [comment]
It's done! Thx for this idea.
